using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;

public class Enemy : MonoBehaviour
{
   public NavMeshAgent agent;
   public Transform player;
   public LayerMask whatIsGround, whatIsPlayer;

    //патрулирование
    public Vector3 walkPoint;
    bool walkPointSet;
    public float walkPointRange;

    //атака
   // public float timeBetweenAttacks;
   // bool alreadyAttacked;

    //состояния
    public float sightRange, attackRange;
    public bool playerInSightRange, playerInAttackRange;

    private void Awake()
    {
        player = GameObject.Find("Player").transform;
        agent = GetComponent<NavMeshAgent>();
    }
    private void Update()
    {
        //игрок в поле зрения или на расстоянии атаки
        playerInSightRange = Physics.CheckSphere(transform.position, sightRange, whatIsPlayer);
        playerInAttackRange = Physics.CheckSphere(transform.position, attackRange, whatIsPlayer);
        if (!playerInSightRange && !playerInAttackRange) Patroling();
        if (playerInSightRange && !playerInAttackRange) ChasePlayer();
       // if (playerInAttackRange && playerInSightRange) AttackPlayer();  
    }
    private void Patroling()
    {
        if (!walkPointSet) SearchWalkPoint();
        if (walkPointSet) 
            agent.SetDestination(walkPoint);
        Vector3 distanseToWalkPoint = transform.position - walkPoint;
        if (distanseToWalkPoint.magnitude < 1f)
            walkPointSet = false;
    }
    private void SearchWalkPoint()
    {
        //подсчет рандома
        float randomZ = Random.Range(-walkPointRange, walkPointRange);
        float randomX = Random.Range(-walkPointRange, walkPointRange);
        walkPoint = new Vector3(transform.position.x + randomX, transform.position.y, transform.position.z + randomZ);
        if (Physics.Raycast(walkPoint, -transform.up, 2f, whatIsGround))
            walkPointSet = true;
    }
    private void ChasePlayer()
    {
        agent.SetDestination(player.position);
    }
    //private void AttackPlayer()
   // {
    //    agent.SetDestination(transform.position);
    //    transform.LookAt(player);
     //   if (!alreadyAttacked)
     //   {
      //      alreadyAttacked = true;
          //  Invoke(nameof(ResetAttack), timeBetweenAttacks);
      //  }
   // }
   // private void ResetAttack()
   // {
   //     alreadyAttacked = false;
    //}
}
